#include <stdio.h>
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 *
 * 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, 144, 233, 377, 610, 987, 1597, 2584
 *
 */

int main(){

    unsigned int a = 1;
    unsigned int b = 1;
    unsigned int c = 0;

    unsigned int limit = 4000000;

    unsigned int sum = 0;

    for(;;){

        c = a + b;
        a = b;
        b = c;

        if(c > limit){

            break;

        } else {

            if(c % 2 == 0){

                printf("%d\n", c);
                sum += c;

            }

        }

   }

   printf("Result: %d\n", sum);

   return 0;
}
